api_platform:
    title: "Creativ'Lab API"
    description: "API For Creativ'Lab Project"
    version: "1.0.0"
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
